### ISSUE TITLE
关于微服务识别用户身份的方法问题

### ISSUE THREAD

**Issue by stick-i** [stick-i/scblogs#104]
现阶段所有服务器（网关除外），识别用户身份都是用的 从Request里获取Header 字段的方法，但这种方法其实不太好，可以改进。

可以单独抽离出一个方法，用于从 Request当中获取用户身份，若获取失败则直接抛出 “用户未登录” 异常即可，当服务需要使用用户信息时，调用该方法获取就好了。

**Comment by gi3636** [comment]
你的用户id不能用token的取吗？何必把id塞到header里去

**Comment by stick-i** [comment]
> 你的用户id不能用token的取吗？何必把id塞到header里去

当然可以，相比您应该不太了解项目当前的运作流程。

token在经过网关后，已经校验并且识别出用户的id了。

若下游服务仍然从token中去拿id，同样还得再校验一次，所以我选择让网关校验后将该信息存起来，下游服务可以放心的使用这个id信息。

**Comment by gi3636** [comment]
明白你的意思了，之前没搞过微服务。

**Comment by stick-i** [comment]
> 明白你的意思了，之前没搞过微服务。

哈哈哈哈，有兴趣搞一搞吗🤣🤣

**Comment by gi3636** [comment]
老实说是有的
