### ISSUE TITLE
前端用户资料缓存问题

### ISSUE THREAD

**Issue by stick-i** [stick-i/scblogs#14]
用户更新头像后，主页右上角显示的用户头像仍然是旧的，没有被刷新，重新登录后头像又被更新了。
可能是没有清除缓存重新获取用户头像

**Comment by nikojxie** [comment]
因为头像url一直是同一个，浏览器缓存导致的该问题，可以通过添加时间戳解决，不过这样会导致一些流量浪费，已提交PR。

项目里个人信息等数据都存在localStorage里，这种全局共用信息建议使用vuex。

**Comment by stick-i** [comment]
> 因为头像url一直是同一个，浏览器缓存导致的该问题，可以通过添加时间戳解决，不过这样会导致一些流量浪费，已提交PR。
> 
> 项目里个人信息等数据都存在localStorage里，这种全局共用信息建议使用vuex。

嘿，非常欢迎你参加这个项目，我已经收到你的pr了，下次提交建议带上截图噢🤣🤣

**Comment by nikojxie** [comment]
@stick-i 哈哈 好的，这个地方我其实更建议每次修改头像换个地址，或者后端接口里处理 加个时间戳这样

**Comment by stick-i** [comment]
@nikojxie 头像的地址是固定用用户名+用户id拼接的🤣🤣， 命名不太好修改，时间戳倒是可以考虑。

另外你可以加一下我们的群聊 729931395 ，方便交流😎😎
