### ISSUE TITLE
注册页面邮箱格式不正确，获取验证码按钮的倒计时还在跑

### ISSUE THREAD

**Issue by liuqiannanyezi** [stick-i/scblogs#150]
### 问题 —— The problem

注册页面邮箱格式不正确，获取验证码按钮的倒计时还在跑
<img width="606" alt="image" src="https://user-images.githubusercontent.com/34704790/215431768-d9b4ede8-c120-4bd7-b746-e7a4481252c0.png">

### 操作环境 —— Operating environment

Google Chrome

### 环境版本 —— Environment version

 109.0.5414.119

### 截图 —— Screenshots

![image](https://user-images.githubusercontent.com/34704790/215431965-fd89ad20-2ae0-43fc-88a5-f6f533124ab9.png)

**Comment by liuqiannanyezi** [comment]
我自己提的 ，我自己解决啦@stick-i

**Comment by stick-i** [comment]
好的，非常感谢你的贡献 @liuqiannanyezi

**Comment by stick-i** [comment]
请提交到这个分支 @liuqiannanyezi 

![image](https://user-images.githubusercontent.com/67500171/215433102-67ce0886-b1e2-4318-bfc0-456e6290cdd0.png)

**Comment by liuqiannanyezi** [comment]
好的

**Comment by stick-i** [comment]
代码已经更新到main分支并部署到服务器上了，再次感谢你的贡献！ @liuqiannanyezi

**Comment by liuqiannanyezi** [comment]
好的@stick-i
