### ISSUE TITLE
Confession wall submission bug

### ISSUE THREAD

**Issue by laity-champion** [stick-i/scblogs#164]
### 问题 —— The problem

非登录用户在表白墙发布内容没有提示是否登录

### 操作环境 —— Operating environment

win10

### 环境版本 —— Environment version

win10 chrome

### 截图 —— Screenshots

![image](https://user-images.githubusercontent.com/82052013/221578524-3dbb26fb-28eb-40a0-a6e7-458c4ba52837.png)

**Comment by laity-champion** [comment]
Confession wall submission bug

**Comment by stick-i** [comment]
你好，此问题由前端代码造成。
如果你打开F12，然后观察Network，你会发现其实并没有任何请求发送出去，另外，前端代码也没有检查用户是否有登录信息。
主要是前端这块还没做完，所以导致功能无法正常使用。

**Comment by stick-i** [comment]
如果你感兴趣，可以看看我们的前端项目重构计划 #149 ，当前issue我就先关闭了
