### ISSUE TITLE
【数据库字段】deleted字段应该设置为is_deleted

### ISSUE THREAD

**Issue by ashlee618** [stick-i/scblogs#173]
### 问题 —— The problem

#137 看到之前有一个issues是专门把is_deleted改为deleted的。
但其实在阿里的《java开发手册》里面明确表示的是：POJO类不能带is前缀，但是数据库字段必须加is前缀
![image](https://user-images.githubusercontent.com/59916531/222310920-78699f8d-e76b-4880-9726-c670ad7a8703.png)
需要我们配置resultMap映射，考虑一下，是不是应该注意下比较好呀

### 操作环境 —— Operating environment

window

### 环境版本 —— Environment version

java8

### 截图 —— Screenshots

![image](https://user-images.githubusercontent.com/59916531/222311162-83c8574b-0ae9-4055-9736-4856e07b6de6.png)

**Comment by stick-i** [comment]
确实是的😢😢，之前理解没到位，不够细心，我再改一版。

非常感谢你的issue🤝😁
