### ISSUE TITLE
个人中心页交互调整

### ISSUE THREAD

**Issue by goodGai** [stick-i/scblogs#207]
### 问题 —— The problem

发表文章后，个人中心页仍展示未发表的文案提示

### 操作环境 —— Operating environment

Chrome

### 环境版本 —— Environment version

 128.0.6613.119

### 重现步骤 —— Steps to reproduce the behavior

个人中心页

### 截图 —— Screenshots

![image](https://github.com/user-attachments/assets/f42ebc5f-aa25-4df9-9f9e-bad6727dce92)

**Comment by goodGai** [comment]
我有兴趣看看这个问题 @stick-i

**Comment by stick-i** [comment]
你看吧，不过需要提醒你的是，这个项目的前端代码挺久没维护了，可能代码质量会比较差一点

**Comment by goodGai** [comment]
那还是重构吧，争取 scblogs-web 替换现有功能

**Comment by stick-i** [comment]
> 那还是重构吧，争取 scblogs-web 替换现有功能

可以的。重构的话，scblogs-web的dev分支是之前有一个朋友重构做的，不过没做多久放弃了。

你看是想自己从头开始重构，还是想接着 scblogs-web的dev分支来弄。

需要提醒你一点，重构前端的工作量也不小，一时半会是搞不完的。

不知道你是出于何种目的想要参与重构，不妨将你的想法说来听听。

**Comment by goodGai** [comment]
接着 scblogs-web dev 分支来弄。
scblogs 太旧了，需要先阅读再调整，而 scblogs-web 直接开发。
这个事情确实不太轻松，我打算慢慢来，有后端、设计稿、接口文档，挺满意的了（如果有前端搭子就更棒了！）。

**Comment by stick-i** [comment]
OK，那你先做吧。前端搭子的话可以到交流群里问问有没有人想做的。

https://github.com/stick-i/scblogs-web/issues/3 已经分配给你，后续我们在那个仓库讨论吧，简单的问题也可以在交流群讨论。

那这边的issue我先关闭了
