### ISSUE TITLE
初次注册时，头像显示不了，访问头像链接也是403

### ISSUE THREAD

**Issue by ifyyf** [stick-i/scblogs#24]

**Comment by sLiKangli** [comment]
这个问题解决了吗，没有我看一下

**Comment by stick-i** [comment]
> 这个问题解决了吗，没有我看一下

@sLiKangli 这个问题，好像已经解决了，你注册账号了吗，要不注册个账号试试🤣，然后如果仍然存在这个问题的话，可以截一些图片贴过来
